### PR TITLE
Allow for duplicate requests when no x-github-delivery header is specified

### PR DESCRIPTION
**Pull request by andy-g**
@JasonEtco here's a proposal for implementing a fix for #76.

### CODE REVIEW

**Comment by 0xR** [comment]
nice! this will make smee useful beyond github hooks as well

**Comment by andy-g** [comment]
Seems like it may be a little more complicated as the `x-github-delivery` header value is also used as the reactjs key for the ListItem:
https://github.com/probot/smee/blob/9d25b48b0f253c6825b50384a5ad9c2ac22f3795/server/src/components/App.js#L169

This warning came back when I added the test, and I expect it may cause additional issues (although all the other tests still pass):
image

**Comment by JasonEtco** [comment]
> Seems like it may be a little more complicated as the x-github-delivery header value is also used as the reactjs key for the ListItem:

Yep - this is because GitHub sends a unique id for every payload. I'd say we fall back to a timestamp in that case, which Smee includes on all payloads:

```js
 const id = item['x-github-delivery']  || item.timestamp
```

**Comment by andy-g** [comment]
> > Seems like it may be a little more complicated as the x-github-delivery header value is also used as the reactjs key for the ListItem:
> 
> Yep - this is because GitHub sends a unique id for every payload. I'd say we fall back to a timestamp in that case, which Smee includes on all payloads:
> 
> ```js
>  const id = item['x-github-delivery']  || item.timestamp
> ```

@JasonEtco I added your suggestion, but the tests are still having the issue, I assume the timestamp property just needs to be added to the test, but I'm on my mobile at the moment, will try have a look at it properly when I have a gap.

**Comment by andy-g** [comment]
It's a pleasure @JasonEtco, thanks for the refinements & merging it in.

**Pull request merged**
