### PR TITLE
Store payloads in localStorage

### LINKED ISSUE #39: Persist deliveries across page loads
I was bummed to see my events disappear when I refreshed the page in my browser. Can we store them in localStorage or something?

### PR DESCRIPTION
**Pull request by JasonEtco**
Created a simple localStorage setup for persisting webhook payloads in the browser. cc @zeke 

Closes #39

### CODE REVIEW

**Comment by JasonEtco** [comment]
> Is this easily testable?

Testable as in in-browser, to try out if it works? You can run Smee locally and use localtunnel to expose it for webhook payloads. If you mean writing tests, I'm not good enough at React component testing to really say if its easily testable.

**Comment by zeke** [comment]
> Testable as in in-browser, to try out if it works? 

I meant automated tests, figuring the answer is "it's not easy".

**Comment by dpritchett** [comment]
I tried jesting this briefly but got stuck in "how even do you test the App component" quicksand.  It seemed doable but not for me, not today.  I have tested basic "saveStateToLocalStorage" and "reloadStateFromLocalStorage" methods in other projects with jest before.

**Comment by JasonEtco** [comment]
@gr2m I thought about using `localForage`; I'm not opposed to it, but we're not doing _that much_. I'm happy to be corrected, but I don't think we need an abstraction over IndexDB for what we're doing.

**Comment by gr2m** [comment]
@JasonEtco yeah on second thought, let’s just move forward, it’s a problem when it’s a problem ™️

**Comment by gr2m** [comment]
> Is there a limit to the size for localstorage

5mb, I think strings are stored as UTF-16, so it’s practically 2.5mb. And reads/writes are synchronous, once you are trying to read out an MB of strings from localStorage, you’ll feel the lag

**Comment by JasonEtco** [comment]
Ok, I'll add a limiter for 30 events, and we can always change that variable as needed 👍

**Comment by zeke** [comment]
Cool to watch this unfold! 🍿

**Comment by JasonEtco** [comment]
I've added some tests 🎉 Coverage has dropped significantly because there's more to the `<App />` component to test, but I don't think thats in the scope of this PR. If y'all are cool with the drop in coverage I can merge this, and I'd like to add some more tests to App in a followup.

**Comment by JasonEtco** [comment]
I have a followup PR in the works for more tests, so I'm going to merge this in. Thanks for the feedback folks 🎉

**Pull request merged**
