### PR TITLE
Proxy Support from CLI #84

### PR DESCRIPTION
**Pull request by HaydenMeloche**
This PR is referencing #84 

## What I've done
- Added CLI param to support passing proxy URL
- Refractored variable name from `proxy` to `path` as my new addition is refering to proxy as well and I don't want others confused

## What I would like to discuss
- Is my variable refactor OK?
- How do I write a test for this? See line 94 in test file.
- Is it possible to test this locally without being behind a proxy?

### CODE REVIEW

**Comment by salah3x** [comment]
Hello @HaydenMeloche, Is there a reason why this PR wasn't merged?

**Comment by schowave** [comment]
Hello, i would like to use the proxy functionality via cli. Why was the PR not merged? Is there any other option how to get smee-client working behind a proxy? Currently when running `smee --url https://smee.io/XXXXXXXXXXX ` I get only connection refused.

**Comment by salah3x** [comment]
@schowave, I managed to get it working by using the smee-client programmatically (within a script) and `bootstrap`ing [global-agent](https://github.com/gajus/global-agent) before calling `smee.start()`

**Comment by schowave** [comment]
> @schowave, I managed to get it working by using the smee-client programmatically (within a script) and `bootstrap`ing [global-agent](https://github.com/gajus/global-agent) before calling `smee.start()`

That sounds good, would you mind to send me your script? Thank you!

**Comment by salah3x** [comment]
Unfortunately, I don't have it anymore, but it's something like this:
```js
const SmeeClient = require('smee-client')
const agent = require('global-agent')

process.env.GLOBAL_AGENT_HTTP_PROXY=http://[IP]:[PORT]
agent.bootstrap()

const smee = new SmeeClient({
  source: 'https://smee.io/[CHANNEL_ID]',
  target: 'http://localhost:3000/events',
  logger: console
})

const events = smee.start()
```
Don't forget to run this:
```
$ npm i smee-client global-agent
```

**Comment by conamalpani** [comment]
Hello ,


I have configured with this code but not able to run, post running getting below error

$ smee -u https://smee.io/AXXXXXXXXXXXX   --path /github-webhook/ --port 8080 --proxy http://1.2.3.4:8080

Forwarding https://smee.io/AXXXXXXXXXXXX   to http://127.0.0.1:8080/github-webhook/
Event { type: 'error', message: 'socket hang up' }
Event { type: 'error', message: 'socket hang up' }
 

new to smee and node, could you please help , thanks in advance.

Thanks,
AM

**Pull request closed without merging**
